apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-${COLOR}
  labels:
    app: myapp
    version: ${COLOR}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: ${COLOR}
  template:
    metadata:
      labels:
        app: myapp
        version: ${COLOR}
    spec:
      containers:
        - name: myapp
          image: ${IMAGE}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
