apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP
  selector:
    app: myapp
    version: blue   # initial value; workflow will patch this to blue/green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
